### ISSUE TITLE
Fix memory leaks

### ISSUE THREAD

**Issue by jmaglic** [jmaglic/MoloVol#53] opened 2020-11-19 11:38 UTC
### Description

I believe the application is currently implemented in a way where smaller memory leaks occur. I don't believe they are large enough to eat up all memory but they should be taken care of eventually.

### Proposed change

I want to analyse the app with an appropriate debugging tool that can show the consumed memory.

**Comment by rlavendomme** [comment] 2020-11-19 12:11
I wonder what makes you think there is memory leaks in the current version of the program.

I tested the program on windows 10 with the task manager open and repeating different calculations with different parameters always lead to the same memory usage at the end of a calculation with a set of parameters.

For example, running the program with isobutane.pdb as input structure and tree depth 4:
grid step 0.1 => 18.4 Mb of RAM
grid step 0.2 => 17.9 Mb of RAM
grid step 0.02 => 38.9 Mb of RAM
back to grid step 0.1 =>18.8 Mb of RAM
back to grid step 0.02 => 38.5 Mb of RAM

Similarly when I use an input file with crystal cell analysis, toggling on/off the unit cell analysis and changing the parameters give consistent RAM usage for each set of parameters.

Do you have a different experience on your computer? Is it caused by a different OS or a different build of wxwidgets and the program (dynamic/static library)?

**Comment by jmaglic** [comment] 2020-11-19 15:50
Some of the higher level components and the atoms are saved as pointers. This memory is never formally cleared up, so I think this could be a memory leak. You might observe an increase in memory consumption if you use a large input files or if you run a calculation many times. But I haven't tested this.

**Comment by rlavendomme** [comment] 2020-11-19 16:18
Indeed, after testing with a protein of 1300 atoms, the RAM usage increases by 0.1 Mb every 5 runs (approximately).

Unless I am mistaken, these potential memory leaks are related to your parts of the code. You use the `new` keywords without using the delete keyword to deallocate the memory used for your pointers.
I'll let you deal with this in due time but it doesn't seem too serious at the moment so I don't think this is a critical issue. Of course, if there is indeed a memory leak, it should be fixed eventually.
Do you know about RAII to avoid memory leaks?

**Closed** 2021-06-03 00:13 UTC
Labels: bug
