### ISSUE TITLE
Calculate Cavity Volume

### ISSUE THREAD

**Issue by jmaglic** [jmaglic/MoloVol#4] opened 2020-06-07 18:43 UTC
New feature to calculate cavity volume. The user should be able to specify a spherical probe (defined by a radius). When setting the voxel types, an additional check needs to determine whether a probe can reach the respective voxel. If so, the type should be altered accordingly.

The user then receives an output on the volume taken up by these voxels. If implemented as such, the final volume will contain all voxels that are a certain distance from other atoms, including voxels "outside" the atom. The following step will then be to differentiate between different cavities.

**Comment by rlavendomme** [comment] 2020-11-18 01:35
For this features, there should be two modes: single probe mode and two probes mode.
The single probe mode serves to determine volume and surface of cavities inside molecules that are isolated from "outside" the molecule.
The two probes mode serves to obtain volume data also for "cavities" that are connected to the "outside" (named pockets, channels and tunnels for biomacromolecules). The second probe is larger and wouldn't fit in the cavities, thus defining the "outside". This is an elegant solution in my opinion with clear definition and reproducible results. This two probes mode is already used by the 3V program ( http://3vee.molmovdb.org/ ).

Moreover, cavities can be defined either by the probe accessible surface or the probe excluded surface leading respectively to the probe accessible volume (accessible to the center of the probe) and the probe occupied volume (accessible to the whole probe).

To illustrate, here are two 2D representations for both modes.
![cavity types 1 probe description](https://user-images.githubusercontent.com/65511614/99466390-9df83c80-293c-11eb-905f-1ac44d89e4ce.png)
![cavity types 2 probes description](https://user-images.githubusercontent.com/65511614/99466405-a6507780-293c-11eb-8c35-ecdd4d4b3558.png)

To obtain these results, each voxel and each octree cube should contain the information about the type of volume that is occupies.
A good solution that will be convenient for lead to lower resource consumption would be to use a single byte variable to identify the voxels and octree cube. Each bit would represent a type of volume and one bit would serve to indicate if the voxel/cube is fully assigned or not.
For example:
```
00000000
||||||||
|||||||V
||||||V Assigned?
|||||V Atom?
||||V Excluded void?
|||V Probe 1 core?
||V Probe 1 shell?
|V Probe 2 core?
V Probe 2 shell?
free bit for later use if necessary
```
Of course, voxels would only contain one single type while octree cubes could contain several types if they contain voxels of different types.
Doing so would allow to run through the grid more efficiently when looking for specific voxel types because octree cubes not containing any voxel of the types we seek would be directly skipped.

Now, to assign the types to each voxel, I would suggest the following algorithms but other algorithms might be more efficient:
1) Single probe mode:
Run through the voxel grid once to assign atom and probe core voxels then run through the voxel grid a second time to assign excluded void and probe shell voxels.

```
// first cycle to assign atom and probe core types
for (each highest octree level cube) {
  double cube_radius;
  if (cube = voxel) { // voxel = lowest octree level
    cube_radius = 0; // the voxel is the smallest volume unit so only its center coordinate should be considered during distance comparison and not its size
  }
  else { // if the cube is an actual octree cube containing several voxels
    cube_radius = sqrt(3*(cube_side/2)^2);
  }
  bool is_away_from_atom = false;
  for (each atom) {
    if ((distance_atom_to_cube_center + cube_radius) < atom_radius) {
      assign the cube and all its sub-cubes and voxels to atom type;
      is_away_from_atom = false;
      break;
    }
    else if ((distance_atom_to_cube_center - cube_radius) > (atom_radius + probe_radius)) {
      is_away_from_atom = true;
    }
    else {
      is_away_from_atom = false;
      check sub-level of the octree with same algorithm
      assign this cube type based on its sub-cubes types
      break;
    }
  }
  if (is_away_from_atom) {
    assign the cube and all its sub-cubes and voxels to probe core type;
  }
}
// second cycle to assign excluded void and probe shell types
// => basically check for unassigned cubes and voxels if they are in the range of a probe core voxel
// if yes, then assign to probe shell, if not, then assign to excluded void
for (each highest octree level cube) {
  double cube_radius;
  if (cube = voxel) { // voxel = lowest octree level
    cube_radius = 0; // the voxel is the smallest volume unit so only its center coordinate should be considered during distance comparison and not its size
  }
  else { // if the cube is an actual octree cube containing several voxels
    cube_radius = sqrt(3*(cube_side/2)^2);
  }
  if (cube_type%2 == 0) { // if it still contains unassigned cubes and voxels
    for (each voxel in the range of the cube center + probe radius) {
      if (voxel is of probe_core type && (distance_cube_center_to_probe_core + cube_radius) < probe_radius) {
        assign the cube and all its sub-cubes and voxels to probe shell type;
        break;
      }
      else {
        check sub-level of the octree with same algorithm
      }
    }
  }
}
// after these two cycles, there shouldn't be any unassigned voxel or cube left
// not tested, need to check if it actually works as intended
```

2) Two probes mode:
The algorithm would be similar but with 4 cycles:
cycle 1: assign atom and probe 2 core types
cycle 2: assign probe 2 shell type
cycle 3: assign probe 1 core type
cycle 4: assign excluded void and probe 1 shell types

3) Differentiate the isolated voids
For probe 1 core and shell types, each isolated cavity should be identified to report separate volumes, surface areas and surface maps.
The simplest solution would be to use a flood fill algorithm but only on probe 1 core + probe 1 shell type voxels.

**Comment by rlavendomme** [comment] 2020-11-18 02:17
Special considerations for crystal unit cell analysis:
1) The code I implemented for the crystal unit cell analysis produces an atom map that will be directly compatible with the algorithms to determine voxel types.
The atom map is the size of an orthogonal cell + atoms surrounding the cell in a useful range for voxel type determination.
Therefore, the only difference will be during the counting of the voxels for the report: only the voxels inside the unit cell should be counted.
If the unit cell sides are not a multiple of the grid step size, then some voxels will have to be partially counted for the volume calculation but this shouldn't be difficult to set up.
 
Illustration in 2D:
![unit cell grid](https://user-images.githubusercontent.com/65511614/99472513-1107b000-2949-11eb-8768-df3a73b8c43e.png)
Red frame = unit cell starting at the origin (0,0 in 2D)
Grid created from origin of unit cell and up to n pixels rounded up above the limits of the unit cell.
Blue squares = pixels fully inside the unit cell.
Green, orange and yellow squares = pixels partially inside the unit cell.
White squares = pixels used in the calculation (contains probes and surrounding atoms) to determine the voxel types but useless for the report.

Example: 
Grid step = 1
Rectangular unit cell
   X = 10.2
   Y = 8.7
Grid size
       0 < x < 11
       0 < y < 9
For each pixel partially in the unit cell, the surface area counted is set to
   0.2*pixel_surface_area, for last line along x (green) 
   0.7*pixel_surface_area, for last line along y (orange)
   0.2*0.7*pixel_surface_area, for Last pixel at the corner of the grid (yellow)

2) Another consideration is related to the flood fill algorithm to identify different cavities.
With the unit cell, the voxels on the sides will be connected because the pattern repeats and loops from one side to another of the unit cell.
It would be quite simple to process this in the flood fill algorithm for crystals with orthogonal space groups but for the other ones, the sides of the orthogonal unit cell generated by the program will loop with an offset. 
Example with simple orthogonal space group:
![looping unit cell orthogonal](https://user-images.githubusercontent.com/65511614/99473979-04388b80-294c-11eb-9b33-e9154b22af68.png)
Example with non orthogonal space group:
The green frame is the orthogonal cell processed in the program.
The pixels of matching colors on the borders of the cell are the looping pixels (notice the offset of two pixels).
![looping unit cell not orthogonal](https://user-images.githubusercontent.com/65511614/99474117-4c57ae00-294c-11eb-880a-4f9ed71f640a.png)

The looping during the flood fill algorithm should be manageable but is not a critical feature for now in my opinion.
Therefore, I would suggest to consider the unit cell as a normal grid for now and use the normal flood fill algorithm without looping.
The feature can be implemented in a future version if necessary.

**Comment by rlavendomme** [comment] 2020-11-20 13:04
Short suggestion regarding the point three of my first message:

> Differentiate the isolated voids
> For probe 1 core and shell types, each isolated cavity should be identified to report separate volumes, surface areas and surface maps.
> The simplest solution would be to use a flood fill algorithm but only on probe 1 core + probe 1 shell type voxels.

Ideally, to identify the different isolated voids in the report, it could be interesting to provide their center of gravity.
It could be done simply in the flood fill algorithm:
For each i j k grid coordinates of voxels belonging to the void, add to three variables total_i, total_j, total_k. Then at the end of flood fill for one void divide by the number of voxels belonging to the void and calibrate based on the grid origin coordinates.
This should, I believe, give x y z coordinates of the center of gravity of the void.

**Comment by rlavendomme** [comment] 2020-11-21 02:06
Another point I would like to raise regarding the identification of different voids:
![cavity identity limit](https://user-images.githubusercontent.com/65511614/99864476-d483c080-2ba3-11eb-92b0-00f1f73786b1.png)
In this figure, we can see that there are three types of probe core volumes in blue because the probe cannot pass through the small gaps in the molecule but the probe shell volumes in green do touch through the gaps.
Therefore, the flood fill algorithm should be written with this kind of special configuration in mind.
My suggestion would be to do the flood fill algorithm only on the probe core voxels (blue). Then, once all different cavities are identified, run through all probe shell voxels (green) => check all voxels within range of probe radius => select the closest probe core voxel and take the same identity. 
If two voxels with same identity are in the same range, keep the first one found. This is easily done with a simple condition such as 

```
if (checked_voxel_type == probe_core && current_distance < saved_distance) { 
saved_distance = current_distance;
probe_shell_voxel_identity = checked_voxel_identity;
}
```
Such an algorithm would effectively cut the green volumes in the middle of the conflicting region.

This algorithm could be implemented directly when voxels type are assigned to probe shell (2nd cycle in the algorithm I suggested above for single probe mode).
Therefore, the full algorithm would be in this order:
- 1st cycle to assign voxels to atom and probe core types
- flood fill algorithm to give identities to different volumes of probe core type
- 2nd cycle to set voxels to assign voxels to excluded void and probe shell types + give identities to the probe shell types at the same time

Any thoughts on the different points I raised?

**Comment by jmaglic** [comment] 2020-12-01 22:45
> My suggestion would be to do the flood fill algorithm only on the probe core voxels (blue). Then, once all different cavities are identified, run through all probe shell voxels (green) => check all voxels within range of probe radius => select the closest probe core voxel and take the same identity.

It makes sense to only flood fill probe core voxels. To assign the shells, I think the shell voxel needs to climb up its voxel tree and then descend once it finds a parent, or a neighbouring voxel that contains the appropriate probe core type. That way we can limit the number of voxels checked. Since we know that the distance between a shell voxels and a core voxels can only be up to the probe radius, we know exactly what parent voxel to climb to to make the search most efficient.

> * 1st cycle to assign voxels to atom and probe core types
> * flood fill algorithm to give identities to different volumes of probe core type
> * 2nd cycle to assign voxels to excluded void and probe shell types + give identities to the probe shell types at the same time

I plan on doing all type assignments necessary for single-probe mode in the first cycle. I don't think it makes sense to develop subsequent code based on an algorithm different to the one that will be employed.

**Comment by rlavendomme** [comment] 2020-12-02 02:48
> I plan on doing all type assignments necessary for single-probe mode in the first cycle. I don't think it makes sense to develop subsequent code based on an algorithm different to the one that will be employed.

It make sense if we manage to find an algorithm that would be more efficient on a single cycle than on 2.
The only issue is that you don't have all atom and probe core voxels so it is difficult to find a rule that will be able to identify which voxels can be set to probe shell. For example, if you check a voxel to know if you can set it to probe shell, you'll look the neighbors but only voxel -1 will be of known type while voxel +1 will still be unidentified. So once voxel +1 is identified, you need to come back on the initial voxel to set it to probe shell.
The two cycles system is convenient because on the second cycle we already have a map of atom an probe core voxels so it is simple to check only the remaining unidentified voxels (=> not a full second cycle). Additionally we know for sure that by looking parent voxels and neighboring voxels, we will directly have the information whether there is a probe core in range or not.

> To assign the shells, I think the shell voxel needs to climb up its voxel tree and then descend once it finds a parent, or a neighbouring voxel that contains the appropriate probe core type. 

I thought of something similar recently but instead of going up, I thought that the second cycle would check voxels going down and at a certain voxel size (2*radius_voxel <= radius_probe), if it contains a probe core, then all unidentified subvoxels are directly assigned to probe shell without having to check the condition individually for each subvoxels. 
If the voxel doesn't contain any probe core but contains unidentified voxels, than it is still necessary to check neighboring voxels. and have an exact distance measurement.

This whole system i's very convenient with the voxel types arranged in a byte. Regarding the last remaining bit that is unused for voxel type in my suggestion above, it could be used to state whether the voxel is mixed or pure. It would reduce the number of conditions checked if we had such a boolean but boolean variables still occupy 1 byte so might as well use the bit we have in voxel type variable.

**Comment by jmaglic** [comment] 2020-12-02 08:55
> The only issue is that you don't have all atom and probe core voxels so it is difficult to find a rule that will be able to identify which voxels can be set to probe shell.
Isn't the probe shell just the overlap between the probe core + the vdW Volume of all atoms with their radii increased by the probe radius? That is easy to get in a single cycle.

> This whole system i's very convenient with the voxel types arranged in a byte.
I plan on implementing this once the cavity volume is functional.

**Comment by rlavendomme** [comment] 2020-12-02 10:47
> Isn't the probe shell just the overlap between the probe core + the vdW Volume of all atoms with their radii increased by the probe radius? That is easy to get in a single cycle.

It is not. Look the figures more carefully. The grey parts (excluded void) are not probe shell but they correspond to the volume of you're describing. The difference must be done to be able to calculate all different volumes and surfaces.

> I plan on implementing this once the cavity volume is functional.

This is fine if you make an algorithm that doesn't rely on this voxel type system. However, if you end up making an algorithm that does rely on it, then you will have to implement it at the same time.
I'll let you see.

**Comment by jmaglic** [comment] 2020-12-02 11:37
> It is not. Look the figures more carefully. The grey parts (excluded void) are not probe shell but they correspond to the volume of you're describing. The difference must be done to be able to calculate all different volumes and surfaces.

Yeah, because they grey parts do not overlap with the probe-accessible volume. My question stands.

**Comment by rlavendomme** [comment] 2020-12-02 12:06
> Yeah, because they grey parts do not overlap with the probe-accessible volume. My question stands.

My bad, I didn't read properly your question and missed the "overlap".
So, yes, the probe shell (green) is indeed the overlap between probe occupied volume (blue + green) and molecular probe accessible volume (red + grey + green). Yet, I still don't see how you'll determine this voxel type within one cycle because you initially only have a map of atoms, not probes.
The two cycle algorithm I proposed, give you a map of atoms and probe centers. Thus it is easy to find what is in range of a probe and what is not.

I might not see something obvious but if you could describe broadly how your algorithm would work for a voxel (the conditions to set the voxel type) then it would be easier to discuss the pros and potential issues.

**Comment by jmaglic** [comment] 2020-12-02 12:37
> I might not see something obvious but if you could describe broadly how your algorithm would work for a voxel

They way it would work is that the voxel cycles through all atoms in vicinity. Against every atom it checks whether it is inside the atom. If it is, then the "atom type" is assigned.

For every atom the voxels also checks, whether it is inside the atom, if its radius was larger by r_probe. If it is, then the voxel remembers that. It's assigned the "potential shell type".

Once a voxel finds an atom that is close enough, it checks whether it's accessible by a hypothetical probe. This algorithm is what I'm currently working on. If the voxel is inaccessible, then this algorithm stops (however, the voxels still checks all other atoms in case it is inside an atom). If the voxel is not inaccessible then it is assigned the probe core type. If it also has or gets the "potential shell type" then it is assigned the "probe shell type".

**Comment by rlavendomme** [comment] 2020-12-02 13:30
You forgot to mention how the algorithm would determine if the voxel is a probe core but it's trivial at this point so I understand why you wouldn't state it.

> Once a voxel finds an atom that is close enough, it checks whether it's accessible by a hypothetical probe. This algorithm is what I'm currently working on. If the voxel is inaccessible, then this algorithm stops (however, the voxels still checks all other atoms in case it is inside an atom). If the voxel is not inaccessible then it is assigned the probe core type. If it also has or gets the "potential shell type" then it is assigned the "probe shell type".

I think this would be highly inefficient because you would need to check many combinations of atoms within 2*probe_radius range of the voxel tagged "potential shell type". Considering that the two probe mode could use probes as large as 5-10 A in radius, the algorithm you propose might need to check several millions of combinations of atoms.
As long as you only keep one atom involved per operation, the algorithm complexity would grow in O(n) with n = number of atoms but if you involve several atoms (let's say x different atoms such as 4), the algorithm would grow in O(n!-(n-x)!) which is close to O(n^x) in cases where all atoms are in range. If only few atoms are in range (let's say z = 10), the complexity would still be O(n*(z!-(z-x)!) which is much higher than O(n). If you take z = 10 and x = 4, you obtain a complexity of O(n*10!-6!) = O(n*5040).

I'll wait to see what is the outcome of your algorithm but I am tempted to make a simple prototype of the algorithm I proposed to compare efficiencies.

**Comment by jmaglic** [comment] 2020-12-02 14:10
The algorithm you proposed scales O(r_p^3) with r_p being the probe radius. You only get linear scaling O(n) if the probe radius remains constant. This is the same with my algorithm. I believe my algorithm can be optimised in multiple ways and has the added benefit of only requiring one cycle through the voxels.

I will continue to implement my algorithm as I see no point in dismissing all work I've done. You are free to make your prototype but be aware that there will likely be a huge number of conflicts when working on the same part of the code.

**Comment by rlavendomme** [comment] 2020-12-02 14:59
> You are free to make your prototype but be aware that there will likely be a huge number of conflicts when working on the same part of the code.

We will only keep one branch, so there shouldn't be any conflict as long as we don't merge prematurely a branch with master.
I could also make this prototype separately in a small program but easily transferable to MoloVol if needed. The efficiency comparison wouldn't be as clear though.

**Closed** 2021-03-30 19:50 UTC
Labels: enhancement
